version: "3.4"

services:
  master:
    build: hadoop-base
    container_name: hadoop-master
    volumes:
      - ./conf:/usr/local/hadoop/conf
  slave1:
    build: hadoop-base
    container_name: hadoop-slave1
    volumes:
      - ./conf:/usr/local/hadoop/conf
  
  slave2:
    build: hadoop-base
    container_name: hadoop-slave2
    volumes:
      - ./conf:/usr/local/hadoop/conf
  
  slave3:
    build: hadoop-base
    container_name: hadoop-slave3
    volumes:
      - ./conf:/usr/local/hadoop/conf

networks:
  default:
    driver: bridge
    #external:
    #  name: host